default: true
MD003:
  style: atx
MD010:
  code_blocks: false
  # code_fences: true
  # indented_code_blocks: false
  # code_block_style: backtick
MD013:
  line_length: 120
  heading_line_length: 80
  code_blocks: false
  tables: false
  headings: true
  strict: false
  stern: false
MD024:
  siblings_only: true
MD029:
  style: one
MD033:
  allowed_elements:
  - center
  - picture
  - source
  - img
  - details
  - summary
MD046:
  style: fenced
