// Code generated by "stringer -type=EventType -trimprefix=EventType"; DO NOT EDIT.

package azure

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeRecordFromEventHub-0]
	_ = x[EventTypeFromLiveLoad-1]
}

const _EventType_name = "RecordFromEventHubFromLiveLoad"

var _EventType_index = [...]uint8{0, 18, 30}

func (i EventType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EventType_index)-1 {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[idx]:_EventType_index[idx+1]]
}
