name: Dependency Review
on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - "**/*.md"
    - docs/**
    - examples/**

permissions: {}

jobs:
  dependency-review:
    name: Dependencies Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        show-progress: false
    - name: Dependency Review
      uses: actions/dependency-review-action@40c09b7dc99638e5ddb0bfd91c1673effc064d8a # v4.8.1
      with:
        fail-on-severity: high
        fail-on-scopes: development,runtime,unknown
        comment-summary-in-pr: on-failure
